doctrine:
    dbal:
        connections:
            default:
                # configure these for your database server
                url: '%env(resolve:DATABASE_PROFILE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4

            profile:
                # configure these for your database server
                url: '%env(resolve:DATABASE_PROFILE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4      

            project:
                # configure these for your database server
                url: '%env(resolve:DATABASE_PROJECT_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4


    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
#               auto_generate_proxy_classes: true
#               naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#                auto_mapping: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Profile'
                        prefix: 'App\Entity\Profile'
                        alias: App
            profile:
                connection: profile
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Profile'
                        prefix: 'App\Entity\Profile'
                        alias: App
            project:
#                auto_generate_proxy_classes: true
                connection: project
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Project'
                        prefix: 'App\Entity\Project'
                        alias: App