version: '3.7'
services:
  db-profile:
    container_name: db-profile
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3319:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: profile
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - ./var/assets/bdd_profile/profile.sql:/docker-entrypoint-initdb.d/profile.sql
      - ./var/assets/bdd_profile/geo.sql:/docker-entrypoint-initdb.d/geo.sql

  db-project:
    container_name: db-project
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3320:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - ./var/assets/bdd_project/project.sql:/docker-entrypoint-initdb.d/project.sql


  apache-php:
    container_name: apache-php
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - "8002:9090"
    depends_on:
      - db-profile
      - db-project

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db-profile
      PMA_PORT: 3319
    ports:
      - '450:80'
